Repository crustio/crust-api, pull requests merged in 2020-06, with the labels that each got.

#18 Create yarn.yml to add CI
  .github/workflows/yarn.yml
Labels: enhancement

#22 [Upgrade] Fix multiple sorder id matching same file bug
  src/app.ts
Labels: bug

#25 [Docs] Update new tee register and work report
  README.md
Labels: documentation
